// Project data — add an entry here to auto-generate onsen gate + stamp slot
export const PROJECTS = [
  {
    id: 'neun',
    name: 'NEUN',
    description: 'AI-powered insurance news aggregation platform with MCP server integration.',
    tags: ['AI', 'MCP', 'News'],
    link: '#',
    position: [18, 0, -14],
  },
  {
    id: 'ibanjiha',
    name: 'IBANJIHA',
    description: 'Telegram bot for community management and automated moderation.',
    tags: ['Telegram', 'Bot', 'Node.js'],
    link: '#',
    position: [-16, 0, -18],
  },
  {
    id: 'joblock',
    name: 'JOBLOCK',
    description: 'Web3 jobs platform with blockchain-verified credentials.',
    tags: ['Web3', 'Supabase', 'Next.js'],
    link: '#',
    position: [22, 0, 14],
  },
  {
    id: 'poreverble',
    name: 'POREVERBLE',
    description: 'Interactive bubble tea ordering experience with playful animations.',
    tags: ['React', 'Animation', 'UX'],
    link: '#',
    position: [-20, 0, 16],
  },
  {
    id: 'proj05',
    name: 'PROJECT 5',
    description: 'Coming soon — a new project is brewing.',
    tags: ['TBD'],
    link: '#',
    position: [0, 0, -28],
  },
  {
    id: 'proj06',
    name: 'PROJECT 6',
    description: 'Coming soon — stay tuned for updates.',
    tags: ['TBD'],
    link: '#',
    position: [0, 0, 28],
  },
];
