// Project data — add an entry here to auto-generate onsen gate + stamp slot
export const PROJECTS = [
  {
    id: 'neun',
    name: 'NEUN',
    shortName: 'NEUN',
    description: 'Web3 job aggregator that tracked 1,000+ live positions from 40+ sources, refreshed every 3 hours. VC-backed companies only — no scams, no rugs. (2025–2026, sunset)',
    tags: ['Next.js', 'Supabase', 'Crawler'],
    link: 'https://github.com/greyisworking/web3-jobs-platform',
    position: [18, 0, -14],
  },
  {
    id: 'ibanjiha',
    name: 'IBANJIHA BOT',
    shortName: 'IBANJIHA',
    description: 'RAG chatbot channeling the voice of queer artist Ibanjiha. Ask anything — get wit, attitude, and occasionally wisdom.',
    tags: ['RAG', 'LLM', 'Chatbot'],
    link: '',
    position: [-16, 0, -18],
  },
  {
    id: 'joblock',
    name: 'JOBLOCK',
    shortName: 'JOBLOCK',
    description: 'Bilateral trust layer for hiring, built on World ID. Solo-built and shipped at the WorldBuild hackathon.',
    tags: ['World ID', 'ZKP', 'Hackathon'],
    link: '',
    position: [22, 0, 14],
  },
  {
    id: 'poreverble',
    name: 'POREVERBLE',
    shortName: 'POREVER',
    description: 'Permanent archive for fan letters, stored on IPFS so they never disappear. Built at the Mantle hackathon.',
    tags: ['IPFS', 'Mantle', 'Hackathon'],
    link: '',
    position: [-20, 0, 16],
  },
  {
    id: 'peer-attestation',
    name: 'PEER ATTESTATION',
    shortName: 'PEER ATT',
    description: "Research talk 'Beyond Trusted Issuers' — analyzing cryptographic flaws in referral-based hiring and proposing a peer attestation framework.",
    tags: ['ZKP', 'Research', 'Talk'],
    link: '',
    position: [0, 0, -28],
  },
  {
    id: 'crypto-literacy',
    name: 'CRYPTO LITERACY',
    shortName: 'CRYPTO LIT',
    description: 'Designed and ran a crypto literacy program at a national insurance training institute — 9 cohorts, 2,000+ learners.',
    tags: ['Education', 'Program Design', 'Web3'],
    link: '',
    position: [0, 0, 28],
  },
];
